### PR TITLE
Add support for configurable timeouts

### PR DESCRIPTION
**Pull request by mateusz-gozdek-sociomantic**
Sometimes it's good to be able to increase it.

In general, I think all variables stored in config file should be
configurable by puppet parameters.

### CODE REVIEW

**Comment by ripienaar** [comment]
good - some test failures though :)

I want to keep this module quite light weight, in the past people drowned in options so only adding the ones needed.  In fact soon there will be no NATS there will only be choria and it will run the broker inside gone from anyone.  But this is a good option to have.

Curious though why did you need to tweak this? machines far away or what?

**Comment by mateusz-gozdek-sociomantic** [comment]
I will take a look at broken tests soon.

Increasing this value seems to be a good workaround for the problem described in choria-io/mcollective-choria#299.

**Comment by ripienaar** [comment]
oh really? that's quite interesting.  Very weird :( I have not had a chance to come back to that issue been working hard on getting some new code up to a good place so I can make new releases of these modules after confirming protocol changes I made will work, soon new releases then time to look at that one.

**Comment by mateusz-gozdek-sociomantic** [comment]
About the tests, I don't really understand what's the problem. Isn't that the problem with the tests itself?

**Comment by ripienaar** [comment]
It's my fault sorry, I should have looked closer!

Do this:

```
-      }.to raise_error(/Puppet AIO Agent 1.5.2 or newer is needed by the ripienaar-nats module/)
+      }.to raise_error(/Puppet AIO Agent 1.5.2 or newer is needed by the choria-nats module/)
```

**Comment by ripienaar** [comment]
(In spec/classes/init_spec.rb)

**Comment by mateusz-gozdek-sociomantic** [comment]
I pushed the update, it looks good now.

**Comment by ripienaar** [comment]
👍

**Pull request merged**
