### PR TITLE
(#25) sysvinit is not a valid service provider on CentOS6

### LINKED ISSUE #25: sysvinit is not a valid service provider on CentOS6
Couple of issues on CentOS 6 master.

- [x] Default  provider on CentOS/RHEL 6 variants is `redhat`
- [x] sysvinit is not a valid provider based on puppet [docs](https://docs.puppet.com/puppet/latest/types/service.html#service-providers). Need to default this to `init` instead.

### PR DESCRIPTION
**Pull request by adastidar**

### CODE REVIEW

**Comment by ripienaar** [comment]
* the `manifests/install/init.pp` needs its class updated
 * what about redhat 6?
 * Could you also update the README?
 * Be great if the commit first line could be `(#xx) fixes blah blah`

**Comment by ripienaar** [comment]
@adastidar still some test fails here :) and a few of the points above valid still too

**Comment by adastidar** [comment]
> @adastidar still some test fails here :) and a few of the points above valid still too

@ripienaar If I remove the default param for `Nats::Service_type`, the module picks up the correct provider from the hiera defaults but the rspec checks fail.

> what about redhat 6?

I dont have a RHEL6 to test this on.

**Comment by ripienaar** [comment]
@adastidar hmm, maybe leave the default then? honestly I know about zero of puppet testing :)

you can just add the same data file as centos 6 for redhat 6 - same content

**Pull request merged**
